const coreMechanics = [
    "Time manipulation",
    "Crafting system",
    "Environmental puzzles",
    "Stealth and evasion",
    "Dynamic weather effects",
    "Day-night cycle",
    "Companion AI",
    "Branching storylines",
    "Moral decision making",
    "Base building",
    "Resource gathering",
    "Skill tree progression",
    "Cooperative multiplayer",
    "Asymmetric multiplayer",
    "Physics-based puzzles",
    "Vehicle combat",
    "Parkour and free running",
    "Summoning and companions",
    "Trading and economy",
    "Farming and agriculture",
    "Dynamic AI encounters",
    "Rhythm-based gameplay",
    "Territory control",
    "Customizable characters",
    "Siege and defense mechanics",
    "Underwater exploration",
    "Mounts and mounted combat",
    "Non-linear exploration",
    "Survival elements",
    "Destructible environments",
    "Secret languages and codes",
    "Magic and spellcasting",
    "Puzzle-platforming",
    "Narrative-driven exploration",
    "Hacking and digital warfare",
    "Espionage and sabotage",
    "Time trials and speed runs",
    "Pet raising and breeding",
    "Gravity manipulation",
    "Dimensional shifts",
    "Social and political simulation",
    "Dynamic ecosystems",
    "In-game photography",
    "Reputation and fame system",
    "Illusion and disguise",
    "Mech and robot customization",
    "Sailing and naval combat",
    "Aerial dogfights",
    "Horror and sanity mechanics",
    "Board game elements",
    "Card battle mechanics",
    "Deck building",
    "Narrative puzzles",
    "Bullet hell combat",
    "Tactical squad management",
    "Augmented reality challenges",
    "Virtual reality immersion",
    "Crowd control and manipulation",
    "Alchemy and potion brewing",
    "Archaeology and relic hunting",
    "Time-loop",
    "Multi-dimensional exploration",
    "Strategic base assaults",
    "Ecosystem",
    "Dual-character control",
    "Memory and flashback sequences",
    "Augmentation and body mods",
	"Dual-wielding combat",
    "Environmental storytelling",
    "Combo-based fighting system",
    "Dynamic faction relationships",
    "Craftable magic spells",
    "In-depth cooking system",
    "Evolving weapon abilities",
    "Player-driven economy",
    "Seasonal world changes",
    "Aging and life cycles",
    "Constructible defenses",
    "Ritualistic magic casting",
    "Moral alignment system",
    "Dynamic quest generation",
    "Reputation-based NPC interaction",
    "Multi-layered armor system",
    "Asymmetrical co-op gameplay",
    "Player-created content",
    "Language learning",
    "Musical instrument playing",
    "Symbiotic relationships with creatures",
    "Adaptive music and sound",
    "Light and shadow stealth mechanics",
    "Advanced climbing and acrobatics",
    "Terrain deformation and construction",
    "Herbology and alchemy",
    "Weather and elemental magic",
    "Psychological warfare and intimidation",
    "NPC memory",
    "Animal taming and breeding",
    "Undercover and disguise gameplay",
    "Crowd dynamics and mob behavior",
    "Realistic wound and medical system",
    "Diplomatic and trade negotiations",
    "Dynamic ecosystem and food chain",
    "Cultural and linguistic diversity",
    "Custom spell creation",
    "Interrogation and persuasion",
    "Astronomy and celestial events",
    "Unique locomotion methods (e.g., grappling hook)",
    "Time dilation effects",
    "Synergy between equipment sets",
    "Multi-dimensional gameplay",
    "Player-driven narrative development",
    "Advanced fluid dynamics",
    "Complex trap-setting mechanics",
    "Kinetic energy-based magic",
    "Resource management and logistics",
    "Dynamic fire propagation",
    "Localized damage and dismemberment",
    "Political intrigue and factions",
    "Non-combat resolution options",
    "Environmental hazards and survival",
    "Symbolic magic (runes, sigils)",
    "Mimicry and illusion magic",
    "Architectural magic (building creation)",
    "Blood magic and sacrifices",
    "Dream manipulation and exploration",
    "Astral projection and spirit walking",
    "Totem and spirit animal guidance",
    "Elemental summoning and control",
    "Time manipulation and paradoxes",
    "Gravity manipulation in puzzles",
    "Portal creation and manipulation",
    "Mind control and influence",
    "Reality warping abilities",
	"Bullet time and slow-motion combat",
    "Cover system for tactical combat",
    "Dialogue trees with branching outcomes",
    "Vehicle driving and combat",
    "Base capture and territory expansion",
    "Dynamic weather affecting gameplay",
    "Photography and investigation",
    "Crafting mini-games",
    "Social simulation and relationship building",
    "Hacking mini-games for unlocking/accessing",
    "Survival mechanics (hunger, thirst, temperature)",
    "Fishing and wildlife hunting",
    "Dynamic building and construction",
    "Physics-based puzzles and challenges",
    "Morality and karma system affecting the game world",
    "Disguise and impersonation for infiltration",
    "Reputation system with factions and NPCs",
    "Day job and life simulation aspects",
    "Rail shooting segments",
    "Tower defense-style base protection",
    "MOBA-like lane pushing and tower destruction",
    "Sports and competition mini-games",
    "Gambling and casino games",
    "Crowd control in large-scale battles",
    "Dynamic crowd behavior and reactions",
    "Flight simulation and aerial combat",
    "Dynamic supply lines and logistics",
    "Music creation and performance",
    "Dance and rhythm challenge sequences",
    "Stealth and shadow mechanics",
    "Narrative-driven puzzle solving",
    "Co-op puzzles requiring player collaboration",
    "Escape room-like enigmas and room escapes",
    "Time-loop mechanics with daily resets",
    "Resource trading and economic systems",
    "Agriculture and farming management",
    "Pet raising and evolution",
    "Dynamic wind and sailing mechanics",
    "Mount breeding and racing",
    "Voice command integration for controls",
    "Drawing and art creation challenges",
    "Customizable companions",
    "Battle royale survival elements",
    "Graffiti and territory marking",
    "Skateboarding and extreme sports",
    "Fitness and exercise challenges",
    "Educational puzzles and trivia",
    "Courtroom and legal battle sequences",
    "Journalism and reporting events",
    "Film making and directing scenes",
    "Fashion and style competitions",
    "Cooking and recipe creation",
    "Singing and voice performance",
    "Stand-up comedy and performance",
    "Magic tricks and illusion challenges",
    "Puppeteering and show management",
    "Archaeology and artifact restoration",
    "Space station management and exploration",
    "Submarine navigation and deep-sea exploration",
	"Sneak",
    "Teleport",
    "Dash",
    "Fly",
    "Float",
    "Glide",
    "Ascend",
    "Descend",
    "Dive",
    "Slither",
    "Hover",
    "Skate",
    "Bounce",
    "Evade",
    "Weave",
	"Dodge or parry",
    "Explosions",
    "Burn",
    "Freeze",
    "Poison",
    "Regenerate",
    "Reflect",
    "Sleep",
	"Mutations",
	"Gardening",
	"Shapeshifting",
	"Weapon forging and customization",
	"Armor and weapon durability",
	"Bounty hunting",
	"Infection or disease",
	"Lockpicking",
	"Echolocation",
	"Morale system",
	"Evolution",
	"Guilds",
	"Gladiator Arena",
	"Spectator interactions",
	"Cryptography",
	"Modular weapon and armor systems for customization",
	"Dynamic NPC schedules and routines",
	"Nemesis system",
	"Cellular automata",
	"Fractal",
	"Legal systems",
    "Economic inflation and deflation",
    "Cultural evolution and spread",
    "Procedural dialect generation",
    "Magical ecosystems",
    "Sentient items",
    "Genetic splicing and mutations",
    "Architectural growth",
    "Interstellar navigation",
    "Planetary terraforming",
    "Mythical beast taming",
    "Invasions",
    "Negotiations",
    "Cartography",
	"Mining and resource extraction"
];

const themesAndSettings = [
    "Fantasy",
    "Sci-Fi",
    "Prehistoric",
    "Post-apocalyptic",
    "Wasteland",
    "Urban",
    "Rural",
    "Medieval",
    "Renaissance",
    "Victorian",
    "Modern",
    "Futuristic",
    "Cyberpunk",
    "Steampunk",
    "Dieselpunk",
    "Biopunk",
    "Mythological",
    "Underwater",
    "Space",
    "Alien planet",
    "Interdimensional",
    "Haunted",
    "Jungle",
    "Desert",
    "Arctic",
    "Mountainous",
    "Island",
    "Underground",
    "Sky",
    "Void",
    "Dreamscape",
    "Historical",
    "Eastern",
    "Western",
    "Nordic",
    "Tropical",
    "Savannah",
    "Forest",
    "Mystical",
    "Gothic",
    "Horror",
    "Lovecraftian",
    "Fairy tale",
    "High school",
    "College",
    "Corporate",
    "Military",
    "Noir",
    "Mystery",
    "Supernatural",
    "Superhero",
    "Dystopian",
    "Utopian",
    "Parallel universe",
    "Time-travel",
    "Virtual reality",
    "Augmented reality",
    "Ancient ruins",
    "Lost civilization",
    "Heist",
    "Espionage",
    "Detective",
    "Zombie apocalypse",
    "Vampire realm",
    "Wizarding world",
    "Robot uprising",
	"Castle",
    "Swamp",
    "Cave",
    "Sky City",
    "Infernal",
    "Celestial",
    "Glacial",
    "Volcanic",
    "Steppes",
    "Metropolis",
    "Suburbia",
    "Slums",
    "Frontier",
    "Prairie",
    "Megalopolis",
    "Arcology",
    "Bazaar",
    "Sanctuary",
    "Ruins",
    "Battleground",
    "Colony",
    "Factory",
    "Harbor",
    "Labyrinth",
    "Library",
    "Mansion",
    "Monastery",
    "Museum",
    "Orchard",
    "Palace",
    "Plantation",
    "Plaza",
    "Prison",
    "Reef",
    "Refinery",
    "River",
    "School",
    "Shrine",
    "Siege",
    "Silo",
    "Station",
    "Temple",
    "Theater",
    "Tomb",
    "Tower",
    "Tundra",
    "Village",
    "Vineyard",
    "Waterfall",
    "Wilderness",
    "Workshop",
    "Zenith",
    "Nadir",
    "Nexus",
    "Oasis",
    "Obelisk",
    "Opera",
    "Outpost",
    "Pagoda",
    "Parliament",
    "Peninsula",
    "Pinnacle",
    "Pit",
    "Planetoid",
    "Plateau",
	"Dystopia",
    "Utopia",
    "Alternate History",
    "Cyberspace",
    "Dream World",
    "Parallel Universe",
    "Magical Realm",
    "Under Siege",
    "Rebellion",
    "Exploration",
    "Survival",
    "Mystery",
    "Espionage",
    "Adventure",
    "War",
    "Peace",
    "Isolation",
    "Revolution",
    "Colonization",
    "Industrial Age",
    "Renaissance Era",
    "Dark Ages",
    "Golden Age",
    "Age of Discovery",
    "Steam Age",
    "Information Age",
    "Space Age",
    "Atomic Age",
    "Mythic Age",
    "Lost World",
    "Apocalypse",
    "Post-Apocalypse",
    "Prehistoric Times",
    "Ancient Civilization",
    "Middle Ages",
    "Victorian Era",
    "Roaring Twenties",
    "Great Depression",
    "World War",
    "Cold War",
    "Modern Day",
    "Near Future",
    "Far Future",
    "Time Travel",
    "Alien Invasion",
    "Supernatural",
    "Fantasy World",
    "Sci-Fi Universe",
    "Cyberpunk Future",
    "Steampunk Past",
    "Lovecraftian Horror",
    "Gothic Horror",
    "Urban Fantasy",
    "Frontier Wilderness",
    "Cosmic Horror",
    "High Fantasy",
    "Low Fantasy",
    "Myth and Legend",
    "Fairy Tale",
    "Superhero Saga",
    "Villainous Lair",
    "Secret Society",
    "Ancient Order",
    "Futuristic Dystopia",
    "Arcane Academy",
    "Galactic Federation",
    "Interstellar Void",
	"Wild West",
	"Pirate",
	"Jurassic",
	"Eldritch",
	"Apocalyptic",
	"Underworld",
	"Circus",
	"Asylum",
	"Atlantis",
	"Submerged",
	"Graveyard",
	"Hell",
	"Garden",
	"Celestial",
    "Necropolis",
    "Limbo",
    "Purgatory",
    "Abyss",
    "Eden",
    "Olympus",
    "Pandemonium",
    "Valhalla",
    "Camelot",
    "Oz",
    "Ragnarok",
    "Yggdrasil",
    "Bardic",
    "Kaiju",
    "Lunar",
    "Nautical",
    "Occult",
    "Psionic",
    "Runic",
    "Solar",
    "Undead",
    "Viking",
    "Witchcraft",
    "Alien",
    "Folklore",
    "Mystic",
    "Nomad",
    "Oracle",
    "Ritual",
    "Spectral",
    "Totem"
];

function getRandomElements(arr, count) {
    const shuffled = arr.sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
}

function generateIdea() {
    const mechanicsCount = parseInt(document.getElementById('mechanicsCount').value);
    const themesCount = parseInt(document.getElementById('themesCount').value);

    const selectedMechanics = getRandomElements(coreMechanics, mechanicsCount);
    const selectedThemes = getRandomElements(themesAndSettings, themesCount);

    let ideaList = '<ul>';
    
    selectedMechanics.forEach(mechanic => {
        ideaList += `<li>${mechanic}</li>`;
    });

    selectedThemes.forEach(theme => {
        ideaList += `<li>${theme}</li>`;
    });

    ideaList += '</ul>';

    document.getElementById('ideaOutput').innerHTML = ideaList;
}

